<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\AnoPDF\AnoPDF.csproj" />
    <ProjectReference Include="..\AnoPDF.Rendering\AnoPDF.Rendering.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <RootNamespace>PdfInspector.Viewer</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
