<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <AssemblyName>AnoPDF.Desktop</AssemblyName>
    <RootNamespace>AnoPDF.Desktop</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="12.0.4" />
    <PackageReference Include="Avalonia.Desktop" Version="12.0.4" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="12.0.4" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="12.0.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AnoPDF.Viewer\AnoPDF.Viewer.csproj" />
  </ItemGroup>

</Project>
